import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import Head from "next/head"; // Mengimpor Head dari next/head

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Balkesmas Wilayah Semarang",
  description: "Generated by create next app",
};

export default function PublicLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/icon.png" />
      </head>
      <body className={inter.className}>
        <Navbar />
        {children}
        <Footer />{" "}
      </body>
    </html>
  );
}
